# Generated by Django 5.2 on 2025-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rol",
            options={},
        ),
        migrations.AddField(
            model_name="rol",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rol",
            name="permisos",
            field=models.TextField(blank=True, default=""),
        ),
    ]
