# Generated by Django 5.2 on 2025-11-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_kardex_log_venta_detalleventa"),
    ]

    operations = [
        migrations.AddField(
            model_name="kardex",
            name="stock_anterior",
            field=models.IntegerField(default=0),
        ),
    ]
