# Generated by Django 5.2 on 2025-11-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_kardex_stock_anterior"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="moneda",
            field=models.CharField(
                choices=[
                    ("COP", "Peso colombiano"),
                    ("USD", "Dólar estadounidense"),
                    ("EUR", "Euro"),
                ],
                default="COP",
                max_length=3,
            ),
        ),
    ]
