# Generated by Django 5.2 on 2025-11-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_venta_estado_alter_producto_moneda"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="iva",
            field=models.DecimalField(decimal_places=4, default=0.19, max_digits=5),
        ),
        migrations.AddField(
            model_name="detalleventa",
            name="precio_con_iva",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="cliente_cedula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="cliente_nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="nit_empresa",
            field=models.CharField(default="202266833-4", max_length=20),
        ),
        migrations.AddField(
            model_name="venta",
            name="numero_factura",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
